experimenting with better timing for un-virtualization
this commit introduces the following test failures:
too many arguments for method __equal: (expr1: Any, expr2: Any)Boolean
test/files/neg/checksensible.scala
test/files/neg/t3736.scala
test/files/pos/t3736.scala
test/files/run/colltest1.scala
test/files/run/unapply.scala

lub error with if:
test/files/pos/t1159.scala
test/files/pos/t4237.scala:3: error: could not find implicit value for parameter i: Int
  (new { def field(implicit i: Int) = 0; def field_=(i: Int) = () }).field = 5 // compiles even with implicit params on getter
test/files/neg/hk-bad-bounds.scala
test/files/run/t498.scala

test/files/specialized/spec-constr.scala:6: error: missing parameter type
    if (f == null) f = { _ => false }

other:
test/files/neg/names-defaults.scala

Conflicts:

	src/compiler/scala/tools/nsc/typechecker/Typers.scala