Test case for rep type inference.
This test fails at the moment with following
compiler message:

virtnew_repinference.scala:4: error: type mismatch;
 found   : Test.Rep[Any]
 required: Test.Rep[Int]
Note: Any >: Int, but class Rep is invariant in type T.
You may wish to define T as -T instead. (SLS 4.5)
    val a = Rep(1)
               ^
one error found

but should work.